### ISSUE TITLE
list_packages failing when finding CMakeLists in the build directory 

### ISSUE THREAD

**Issue by dhood** [ament/ament_tools#117]
I am calling `ament list_packages` from the base of a ROS 2 workspace. In this directory I have `src`, `build_isolated` and `install_isolated` directories.

I get the following error:
```
dhood@osrf-esteve:~/ros2_ws-flake8 [ros2_ws-flake8]$ ament list_packages
Traceback (most recent call last):
  File "/home/dhood/ros2_ws-flake8/install_isolated/ament_tools/bin/ament", line 9, in <module>
    load_entry_point('ament-tools==0.0.0', 'console_scripts', 'ament')()
  File "/home/dhood/ros2_ws-flake8/install_isolated/ament_tools/lib/python3.5/site-packages/ament_tools/commands/ament.py", line 88, in main
    rc = args.main(args)
  File "/home/dhood/ros2_ws-flake8/install_isolated/ament_tools/lib/python3.5/site-packages/ament_tools/verbs/list_packages.py", line 87, in main
    package = package or parse_package(package_abs_path)
  File "/home/dhood/ros2_ws-flake8/install_isolated/ament_tools/lib/python3.5/site-packages/ament_tools/package_types/__init__.py", line 31, in parse_package
    pkg = package_type['parse_package'](path)
  File "/home/dhood/ros2_ws-flake8/install_isolated/ament_tools/lib/python3.5/site-packages/ament_tools/package_types/cmake.py", line 33, in parse_package
    data = extract_data(cmakelists)
  File "/home/dhood/ros2_ws-flake8/install_isolated/ament_tools/lib/python3.5/site-packages/ament_tools/package_types/cmake.py", line 47, in extract_data
    raise RuntimeError("Failed to extract project name from '%s'" % cmakelists)
RuntimeError: Failed to extract project name from './build_isolated/test_rclcpp/test_rclcpp__py/CMakeLists.txt'
```

That `CMakeLists.txt` is in the build directory and is just being used [as part of a package's build process](https://github.com/ros2/rosidl/blob/000e26e7db092ea31336c00969f36e958e4924b6/rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake#L155), it's never installed.

Would it make sense to specify that the build and build_isolated directories be excluded [when find_package_paths is called](https://github.com/ament/ament_tools/blob/b818eac166e39fc067865294cd7f466bc010790a/ament_tools/verbs/list_packages.py#L73) for the list verb? 
Perhaps that should be the default in the [`find_package_paths`](https://github.com/ament/ament_tools/blob/1a87a3bdf0d96d3c6c3b0d604478c3b715a363c1/ament_tools/packages.py#L23)?

**Comment by dirk-thomas** [comment]
The `list_packages` verb has no information about build spaces and the user can choose any name for it. Therefore it can't ignore them. Instead the `build` verb can drop an `AMENT_IGNORE` file in the build space. See #118.

**Comment by dhood** [comment]
That does sound like a better idea. I can confirm that #118 fixes this thanks
