### ISSUE TITLE
Errors using ament uninstall

### ISSUE THREAD

**Issue by dhood** [ament/ament_tools#90]
Following error happens on osx and trusty (at least) with any set of arguments

```
14:34:37 deanna /Users/deanna/ros2_ws
$ src-master/ament/ament_tools/scripts/ament.py uninstall --only-package rmw_connext_cpp
Traceback (most recent call last):
  File "src-master/ament/ament_tools/scripts/ament.py", line 149, in <module>
    sys.exit(main() or 0)
  File "/Users/deanna/ros2_ws/src-master/ament/ament_tools/ament_tools/commands/ament.py", line 88, in main
    rc = args.main(args)
  File "/Users/deanna/ros2_ws/src-master/ament/ament_tools/ament_tools/verbs/uninstall/cli.py", line 90, in main
    print_topological_order(opts, packages)
  File "/Users/deanna/ros2_ws/src-master/ament/ament_tools/ament_tools/verbs/build/cli.py", line 172, in print_topological_order
    opts.skip_packages = opts.skip_packages or []
AttributeError: 'Namespace' object has no attribute 'skip_packages'
```

Think the cause is similar to https://github.com/ament/ament_tools/issues/84 but haven't looked into it yet

**Comment by dirk-thomas** [comment]
#91 should address this problem.

**Comment by dhood** [comment]
as long as the skip-packages argument is not supposed to work with uninstall

**Comment by dirk-thomas** [comment]
Since it currently doesn't have the command line argument I would say its fine. We can add it if we want to now or later.

**Comment by dhood** [comment]
OK, sounds fair
